// Generated by gencpp from file yeet_msgs/move.msg
// DO NOT EDIT!


#ifndef YEET_MSGS_MESSAGE_MOVE_H
#define YEET_MSGS_MESSAGE_MOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yeet_msgs
{
template <class ContainerAllocator>
struct move_
{
  typedef move_<ContainerAllocator> Type;

  move_()
    : drive(0)
    , turn(0)  {
    }
  move_(const ContainerAllocator& _alloc)
    : drive(0)
    , turn(0)  {
  (void)_alloc;
    }



   typedef int8_t _drive_type;
  _drive_type drive;

   typedef int8_t _turn_type;
  _turn_type turn;





  typedef boost::shared_ptr< ::yeet_msgs::move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yeet_msgs::move_<ContainerAllocator> const> ConstPtr;

}; // struct move_

typedef ::yeet_msgs::move_<std::allocator<void> > move;

typedef boost::shared_ptr< ::yeet_msgs::move > movePtr;
typedef boost::shared_ptr< ::yeet_msgs::move const> moveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yeet_msgs::move_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yeet_msgs::move_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yeet_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'yeet_msgs': ['/home/trey/intro_robotics_ws/src/yeet_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yeet_msgs::move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yeet_msgs::move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yeet_msgs::move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yeet_msgs::move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yeet_msgs::move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yeet_msgs::move_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yeet_msgs::move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f1cddb8ef3caea21484489b8f1096b9";
  }

  static const char* value(const ::yeet_msgs::move_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f1cddb8ef3caea2ULL;
  static const uint64_t static_value2 = 0x1484489b8f1096b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::yeet_msgs::move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yeet_msgs/move";
  }

  static const char* value(const ::yeet_msgs::move_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yeet_msgs::move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 drive\n\
int8 turn\n\
";
  }

  static const char* value(const ::yeet_msgs::move_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yeet_msgs::move_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive);
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yeet_msgs::move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yeet_msgs::move_<ContainerAllocator>& v)
  {
    s << indent << "drive: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drive);
    s << indent << "turn: ";
    Printer<int8_t>::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YEET_MSGS_MESSAGE_MOVE_H
