// Generated by gencpp from file reactive_robot/autodrive.msg
// DO NOT EDIT!


#ifndef REACTIVE_ROBOT_MESSAGE_AUTODRIVE_H
#define REACTIVE_ROBOT_MESSAGE_AUTODRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reactive_robot
{
template <class ContainerAllocator>
struct autodrive_
{
  typedef autodrive_<ContainerAllocator> Type;

  autodrive_()
    : collision(false)  {
    }
  autodrive_(const ContainerAllocator& _alloc)
    : collision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collision_type;
  _collision_type collision;





  typedef boost::shared_ptr< ::reactive_robot::autodrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reactive_robot::autodrive_<ContainerAllocator> const> ConstPtr;

}; // struct autodrive_

typedef ::reactive_robot::autodrive_<std::allocator<void> > autodrive;

typedef boost::shared_ptr< ::reactive_robot::autodrive > autodrivePtr;
typedef boost::shared_ptr< ::reactive_robot::autodrive const> autodriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reactive_robot::autodrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reactive_robot::autodrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reactive_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'reactive_robot': ['/home/jkleiber/intro_robotics_ws/src/reactive_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reactive_robot::autodrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactive_robot::autodrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_robot::autodrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_robot::autodrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_robot::autodrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_robot::autodrive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reactive_robot::autodrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec9653804a13642f770edbe4a85843b2";
  }

  static const char* value(const ::reactive_robot::autodrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec9653804a13642fULL;
  static const uint64_t static_value2 = 0x770edbe4a85843b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::reactive_robot::autodrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reactive_robot/autodrive";
  }

  static const char* value(const ::reactive_robot::autodrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reactive_robot::autodrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool collision\n\
";
  }

  static const char* value(const ::reactive_robot::autodrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reactive_robot::autodrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct autodrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reactive_robot::autodrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reactive_robot::autodrive_<ContainerAllocator>& v)
  {
    s << indent << "collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REACTIVE_ROBOT_MESSAGE_AUTODRIVE_H
