// Generated by gencpp from file reactive_robot/keyboard_overrideResponse.msg
// DO NOT EDIT!


#ifndef REACTIVE_ROBOT_MESSAGE_KEYBOARD_OVERRIDERESPONSE_H
#define REACTIVE_ROBOT_MESSAGE_KEYBOARD_OVERRIDERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reactive_robot
{
template <class ContainerAllocator>
struct keyboard_overrideResponse_
{
  typedef keyboard_overrideResponse_<ContainerAllocator> Type;

  keyboard_overrideResponse_()
    : overridden(false)  {
    }
  keyboard_overrideResponse_(const ContainerAllocator& _alloc)
    : overridden(false)  {
  (void)_alloc;
    }



   typedef uint8_t _overridden_type;
  _overridden_type overridden;





  typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> const> ConstPtr;

}; // struct keyboard_overrideResponse_

typedef ::reactive_robot::keyboard_overrideResponse_<std::allocator<void> > keyboard_overrideResponse;

typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideResponse > keyboard_overrideResponsePtr;
typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideResponse const> keyboard_overrideResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reactive_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'reactive_robot': ['/home/jkleiber/intro_robotics_ws/src/reactive_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb5aa041e0dc2943641ab2f5d3442948";
  }

  static const char* value(const ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb5aa041e0dc2943ULL;
  static const uint64_t static_value2 = 0x641ab2f5d3442948ULL;
};

template<class ContainerAllocator>
struct DataType< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reactive_robot/keyboard_overrideResponse";
  }

  static const char* value(const ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool overridden\n\
";
  }

  static const char* value(const ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.overridden);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keyboard_overrideResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reactive_robot::keyboard_overrideResponse_<ContainerAllocator>& v)
  {
    s << indent << "overridden: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overridden);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REACTIVE_ROBOT_MESSAGE_KEYBOARD_OVERRIDERESPONSE_H
