// Generated by gencpp from file reactive_robot/keyboard_overrideRequest.msg
// DO NOT EDIT!


#ifndef REACTIVE_ROBOT_MESSAGE_KEYBOARD_OVERRIDEREQUEST_H
#define REACTIVE_ROBOT_MESSAGE_KEYBOARD_OVERRIDEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reactive_robot
{
template <class ContainerAllocator>
struct keyboard_overrideRequest_
{
  typedef keyboard_overrideRequest_<ContainerAllocator> Type;

  keyboard_overrideRequest_()
    {
    }
  keyboard_overrideRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> const> ConstPtr;

}; // struct keyboard_overrideRequest_

typedef ::reactive_robot::keyboard_overrideRequest_<std::allocator<void> > keyboard_overrideRequest;

typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideRequest > keyboard_overrideRequestPtr;
typedef boost::shared_ptr< ::reactive_robot::keyboard_overrideRequest const> keyboard_overrideRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reactive_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'reactive_robot': ['/home/jkleiber/intro_robotics_ws/src/reactive_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reactive_robot/keyboard_overrideRequest";
  }

  static const char* value(const ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keyboard_overrideRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::reactive_robot::keyboard_overrideRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // REACTIVE_ROBOT_MESSAGE_KEYBOARD_OVERRIDEREQUEST_H
